development:
  adapter: postgresql
  encoding: unicode
  database: CodeRunner_development
  host: localhost
  port: 5432
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: CodeRunner_test
  host: localhost
  port: 5432
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: CodeRunner_production
  pool: 5

cucumber:
  <<: *test
