require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ElevatorPitchesController do

  # This should return the minimal set of attributes required to create a valid
  # ElevatorPitch. As you add validations to ElevatorPitch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "text" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ElevatorPitchesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all elevator_pitches as @elevator_pitches" do
      elevator_pitch = ElevatorPitch.create! valid_attributes
      get :index, {}, valid_session
      assigns(:elevator_pitches).should eq([elevator_pitch])
    end
  end

  describe "GET show" do
    it "assigns the requested elevator_pitch as @elevator_pitch" do
      elevator_pitch = ElevatorPitch.create! valid_attributes
      get :show, {:id => elevator_pitch.to_param}, valid_session
      assigns(:elevator_pitch).should eq(elevator_pitch)
    end
  end

  describe "GET new" do
    it "assigns a new elevator_pitch as @elevator_pitch" do
      get :new, {}, valid_session
      assigns(:elevator_pitch).should be_a_new(ElevatorPitch)
    end
  end

  describe "GET edit" do
    it "assigns the requested elevator_pitch as @elevator_pitch" do
      elevator_pitch = ElevatorPitch.create! valid_attributes
      get :edit, {:id => elevator_pitch.to_param}, valid_session
      assigns(:elevator_pitch).should eq(elevator_pitch)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ElevatorPitch" do
        expect {
          post :create, {:elevator_pitch => valid_attributes}, valid_session
        }.to change(ElevatorPitch, :count).by(1)
      end

      it "assigns a newly created elevator_pitch as @elevator_pitch" do
        post :create, {:elevator_pitch => valid_attributes}, valid_session
        assigns(:elevator_pitch).should be_a(ElevatorPitch)
        assigns(:elevator_pitch).should be_persisted
      end

      it "redirects to the created elevator_pitch" do
        post :create, {:elevator_pitch => valid_attributes}, valid_session
        response.should redirect_to(ElevatorPitch.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved elevator_pitch as @elevator_pitch" do
        # Trigger the behavior that occurs when invalid params are submitted
        ElevatorPitch.any_instance.stub(:save).and_return(false)
        post :create, {:elevator_pitch => { "text" => "invalid value" }}, valid_session
        assigns(:elevator_pitch).should be_a_new(ElevatorPitch)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ElevatorPitch.any_instance.stub(:save).and_return(false)
        post :create, {:elevator_pitch => { "text" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested elevator_pitch" do
        elevator_pitch = ElevatorPitch.create! valid_attributes
        # Assuming there are no other elevator_pitches in the database, this
        # specifies that the ElevatorPitch created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ElevatorPitch.any_instance.should_receive(:update).with({ "text" => "MyText" })
        put :update, {:id => elevator_pitch.to_param, :elevator_pitch => { "text" => "MyText" }}, valid_session
      end

      it "assigns the requested elevator_pitch as @elevator_pitch" do
        elevator_pitch = ElevatorPitch.create! valid_attributes
        put :update, {:id => elevator_pitch.to_param, :elevator_pitch => valid_attributes}, valid_session
        assigns(:elevator_pitch).should eq(elevator_pitch)
      end

      it "redirects to the elevator_pitch" do
        elevator_pitch = ElevatorPitch.create! valid_attributes
        put :update, {:id => elevator_pitch.to_param, :elevator_pitch => valid_attributes}, valid_session
        response.should redirect_to(elevator_pitch)
      end
    end

    describe "with invalid params" do
      it "assigns the elevator_pitch as @elevator_pitch" do
        elevator_pitch = ElevatorPitch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ElevatorPitch.any_instance.stub(:save).and_return(false)
        put :update, {:id => elevator_pitch.to_param, :elevator_pitch => { "text" => "invalid value" }}, valid_session
        assigns(:elevator_pitch).should eq(elevator_pitch)
      end

      it "re-renders the 'edit' template" do
        elevator_pitch = ElevatorPitch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ElevatorPitch.any_instance.stub(:save).and_return(false)
        put :update, {:id => elevator_pitch.to_param, :elevator_pitch => { "text" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested elevator_pitch" do
      elevator_pitch = ElevatorPitch.create! valid_attributes
      expect {
        delete :destroy, {:id => elevator_pitch.to_param}, valid_session
      }.to change(ElevatorPitch, :count).by(-1)
    end

    it "redirects to the elevator_pitches list" do
      elevator_pitch = ElevatorPitch.create! valid_attributes
      delete :destroy, {:id => elevator_pitch.to_param}, valid_session
      response.should redirect_to(elevator_pitches_url)
    end
  end

end
