require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RequestAttachmentsController do

  # This should return the minimal set of attributes required to create a valid
  # RequestAttachment. As you add validations to RequestAttachment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "request" => Fabricate(:request) } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RequestAttachmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all request_attachments as @request_attachments" do
      request_attachment = RequestAttachment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:request_attachments).should eq([request_attachment])
    end
  end

  describe "GET show" do
    it "assigns the requested request_attachment as @request_attachment" do
      request_attachment = RequestAttachment.create! valid_attributes
      get :show, {:id => request_attachment.to_param}, valid_session
      assigns(:request_attachment).should eq(request_attachment)
    end
  end

  describe "GET new" do
    it "assigns a new request_attachment as @request_attachment" do
      get :new, {}, valid_session
      assigns(:request_attachment).should be_a_new(RequestAttachment)
    end
  end

  describe "GET edit" do
    it "assigns the requested request_attachment as @request_attachment" do
      request_attachment = RequestAttachment.create! valid_attributes
      get :edit, {:id => request_attachment.to_param}, valid_session
      assigns(:request_attachment).should eq(request_attachment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RequestAttachment" do
        expect {
          post :create, {:request_attachment => valid_attributes}, valid_session
        }.to change(RequestAttachment, :count).by(1)
      end

      it "assigns a newly created request_attachment as @request_attachment" do
        post :create, {:request_attachment => valid_attributes}, valid_session
        assigns(:request_attachment).should be_a(RequestAttachment)
        assigns(:request_attachment).should be_persisted
      end

      it "redirects to the created request_attachment" do
        post :create, {:request_attachment => valid_attributes}, valid_session
        response.should redirect_to(RequestAttachment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved request_attachment as @request_attachment" do
        # Trigger the behavior that occurs when invalid params are submitted
        RequestAttachment.any_instance.stub(:save).and_return(false)
        post :create, {:request_attachment => { "request" => "invalid value" }}, valid_session
        assigns(:request_attachment).should be_a_new(RequestAttachment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RequestAttachment.any_instance.stub(:save).and_return(false)
        post :create, {:request_attachment => { "request" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      before { @request = Fabricate(:request) }
      it "updates the requested request_attachment" do
        request_attachment = RequestAttachment.create! valid_attributes
        # Assuming there are no other request_attachments in the database, this
        # specifies that the RequestAttachment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RequestAttachment.any_instance.should_receive(:update).with({ "request" => @request })
        put :update, {:id => request_attachment.to_param, :request_attachment => { "request" => @request }}, valid_session
      end

      it "assigns the requested request_attachment as @request_attachment" do
        request_attachment = RequestAttachment.create! valid_attributes
        put :update, {:id => request_attachment.to_param, :request_attachment => valid_attributes}, valid_session
        assigns(:request_attachment).should eq(request_attachment)
      end

      it "redirects to the request_attachment" do
        request_attachment = RequestAttachment.create! valid_attributes
        put :update, {:id => request_attachment.to_param, :request_attachment => valid_attributes}, valid_session
        response.should redirect_to(request_attachment)
      end
    end

    describe "with invalid params" do
      it "assigns the request_attachment as @request_attachment" do
        request_attachment = RequestAttachment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RequestAttachment.any_instance.stub(:save).and_return(false)
        put :update, {:id => request_attachment.to_param, :request_attachment => { "request" => "invalid value" }}, valid_session
        assigns(:request_attachment).should eq(request_attachment)
      end

      it "re-renders the 'edit' template" do
        request_attachment = RequestAttachment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RequestAttachment.any_instance.stub(:save).and_return(false)
        put :update, {:id => request_attachment.to_param, :request_attachment => { "request" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested request_attachment" do
      request_attachment = RequestAttachment.create! valid_attributes
      expect {
        delete :destroy, {:id => request_attachment.to_param}, valid_session
      }.to change(RequestAttachment, :count).by(-1)
    end

    it "redirects to the request_attachments list" do
      request_attachment = RequestAttachment.create! valid_attributes
      delete :destroy, {:id => request_attachment.to_param}, valid_session
      response.should redirect_to(request_attachments_url)
    end
  end

end
